#!/bin/bash

path=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
action=""
network=""
version="v2.1.2"
github_version_count=0
kill_attempt_count=15
script_name="bahamut_validator"
network_name="sahara oasis"
projects="validator"
download_path="$path/download"
min_sync_peers="min-sync-peers 1"

github_binaries="fastexlabs/binaries"
binaries_tags_url="https://api.github.com/repos/$github_binaries/tags"
binaries_releases_url="https://api.github.com/repos/$github_binaries/releases/tags/${version}"
bahamut_validator_script_url="https://github.com/${github_binaries}/raw/master/${script_name}"

fee_recipient=""
validator_keys_dir=""
public_keys=""

declare -A ports
ports=( [sahara.rpc-port]=4000
        [oasis.rpc-port]=4001 )

declare -A project_pids
for i in $projects; do
    pid=$(pidof $i | xargs pwdx 2>&1 | grep "$path" | cut -d: -f1)
    pid_path=$(pidof $i | xargs pwdx 2>&1 | grep "$path" | cut -d: -f2 | sed 's/^ *//')
    for j in $pid_path; do
        if [ "$path" == "$j" ]; then
            for c in $pid; do
                for f in $network_name; do
                    if ps -fp "$c" | grep "$f" > /dev/null 2>&1; then
                        project_pids["${f}_${i}_pid"]="$c"
                    fi
                done
            done
        fi
    done
done

function red()
{
    echo -e "\033[91m$1\033[0m"
}

function green()
{
    echo -e "\033[92m$1\033[0m"
}

function yellow()
{
    echo -e "\033[93m$1\033[0m"
}

function blue()
{
    echo -e "\033[94m$1\033[0m"
}

function yellow()
{
    echo -e "\033[33m$1\033[0m"
}

function error
{
    echo "$(red "Error: ")$1"
}

function warning
{
    echo "$(blue "Warning: ")$1"
}

function info
{
    echo "$(green "Info: ")$1"
}

function conf
{
    echo "$(yellow "Conf: ")$1"
}

function start_spinner
{
    set +m
    echo -ne $(info "${1}")
    while : ; do
        for X in / - \\ \|; do
            echo -en "\b$X"
            sleep 0.1
        done
    done & 2>/dev/null
    spinner_pid=$!
}

function stop_spinner
{
    { kill -9 $spinner_pid && wait; } 2>/dev/null
    set -m
    echo -en "\033[2K\r"
}

function print_help
{
    echo "BAHAMUT"
    echo -e "\n"
    #Name
    echo "NAME:"
    echo -e "\tbahamut"
    #DESCRIPTION
    echo -e "\n"
    echo "DESCRIPTION:"
    echo -e "\tThis script automatically sets up and runs validator of Fastex chain (Bahamut) blockchain."
    #Usage
    echo -e "\n"
    echo "USAGE:"
    echo -e "\tbahamut OPTIONS [arguments]" 
    #Mandatory options
    echo -e "\n"
    echo "MANDATORY OPTIONS:"
    echo -e "\tinstall|start|stop|restart|list|update|reset|remove|import|exit - Main action(s) to be performed."
    echo -e "\tstart - Starts the validator client"
    echo -e "\tstop - Stops the validator client."
    echo -e "\tlist - Returns the list of the imported validators."
    echo -e "\tinstall - Installs the validator client dependencies needed for the start."
    echo -e "\tupdate - Updates validator client binaries and native scripts."
    echo -e "\treset - Resets the validator client databases."
    echo -e "\tremove - Removes the imported validators."
    #Arguments
    echo -e "\n"
    echo "ARGUMENTS:"
    echo -e "\t--help, -h - Show help."
    echo -e "\t--version, -v - Manually set the binaries version. Default version is the latest version."
    echo -e "\t-n, --network - Must connect to the network. Network can be Sahara (mainnet) or Oasis (testnet)."
	echo -e "\t--fee-recipient - Fee Recipient address."
	echo -e "\t--validator-keys-dir - Validator keys directory"
	echo -e "\t--public-keys - Validator's public keys"
    #Examples
    echo -e "\n"
    echo -e "EXAMPLES:"
    echo -e "\t- ./bahamut_validator start -n=oasis"
	echo -e "\t\t Start oasis node. If there are no dependencies necessary for start, it is necessary to install first. Example ./bahamut_validator install."
    echo -e "\n"
    echo -e "\t- ./bahamut_validator update --version v1.0.0"
    echo -e "\t\t Update bahamut script with binaries v1.0.0 version. If there is a running process, terminate it with Stop action. Example ./bahamut_validator stop."
    echo -e "\n"
    echo -e "\t- ./bahamut_validator stop"
    echo -e "\t\t If Sahara and Oasis are running at the same time, specify which network to swich off. Example ./bahamut_validator stop --network oasis."
    echo -e "\n"
	echo -e "\t- ./bahamut_validator restart"
    echo -e "\t\t If Sahara and Oasis are running at the same time, specify which network to restart. Example ./bahamut_validator restart --network oasis."
    echo -e "\n"
    echo -e "\t- ./bahamut_validator reset"
    echo -e "\t\t If neither Sahara nor Oasis network is specified, both databases will be reset. In order to reset one of them, provide the network name. Example ./bahamut_validator reset -n=oasis."
    #Systemctl commands
    echo -e "\n"
    echo -e "SYSTEMCTL COMMANDS EXAMPLES:"
    echo -e "\tsudo systemctl start bahamut_oasis_validator.service - Start the validator client."
    echo -e "\tsudo systemctl stop bahamut_sahara_validator.service - Stop the validator client."
    echo -e "\n"
}

function check_network()
{
    if [ -z "$network" ]; then
        error "Network is mandatory option during start. Type --help or -h to see the correct options."
        exit 1
    fi
    if [  "mainnet" != "$network" ] && [ "oasis" != "$network" ] && [ "sahara" != "$network" ]; then
        error "Network name must be \"mainnet\",\"oasis\",\"sahara\"."
        exit 1
    fi
}

function check_fee_recipient
{
	if [ -z "$fee_recipient" ]; then
        error "Fee recipient is mandatory option during start. Type --help or -h to see the correct options."
        exit 1
	fi
	if ! [ 42 -eq ${#fee_recipient} ]; then
        error "Fee recipient must be 20 bytes length address with `0x` prefix"
        exit 1
	fi
	if ! [ "0x" = ${fee_recipient:0:2} ]; then
        error "Fee recipient must be 20 bytes length address with `0x` prefix"
        exit 1
	fi
}


function check_action
{
    if ! [ -z "$action" ]; then
        error "Please specify only one of start|stop|status|restart|install|update options!!!"
        exit 1
    fi
}

function get_shift()
{
    if [[ $1 != *"="* ]]; then
        echo 2
    else
        echo 1
    fi
}

function get_option()
{
    if [[ $1 != *"="* ]]; then
        echo "$2"
    else
        echo "${1#*=}"
    fi
}

function read_fee_recipient
{
	if [ -z "$fee_recipient" ]; then
		while [ true ]; do
			read -p "Please enter your fee recipient address: " v
			echo $v
			if ! [[ 42 -eq ${#v} ]]; then
				error "Fee recipient must be 20 bytes length address with \'0x\' prefix"
				continue
			fi
			if ! [[ "0x" -eq ${v:0:2} ]]; then
				error "Fee recipient must be 20 bytes length address with \'0x\' prefix"
				continue
			fi
			fee_recipient=$v
			break
		done
	fi
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            print_help
            exit 0
            ;;
        -n|--network|-n=*|--network=*)
            network=$(get_option $1 $2)
            shift $(get_shift $1)
            check_network
            ;;
		--fee-recipient|--fee-recipient=*)
            fee_recipient=$(get_option $1 $2)
            shift $(get_shift $1)
			;;
		--validator-keys-dir|--validator-keys-dir=*)
            validator_keys_dir=$(get_option $1 $2)
            shift $(get_shift $1)
			;;
		--public-keys|--public-keys=*)
            public_keys=$(get_option $1 $2)
            shift $(get_shift $1)
			;;
        -v|--version|-v=*|--version=*)
            version=$(get_option $1 $2)
            shift $(get_shift $1)
            ((github_version_count=github_version_count + 1))
            ;;
        start|stop|list|restart|install|update|reset|exit|import|remove)
            check_action
            action=$1
            shift
            ;;
        *)
            error "Unknown option $1. Type --help or -h to see the correct options."
            exit 1
            ;;
    esac
done

if [ -z "$action" ]; then
    error "Main action \"start\", \"stop\", \"status\", \"restart\", \"install\", \"update\", \"reset\" is missing!!!"
    info "For more details please use -h|--help option."
    exit 1
fi

##############################################
#This is done for users who ran the script on the mainnet
if [ -z "${project_pids["oasis_execution_pid"]}" ] && [ -z "${project_pids["sahara_execution_pid"]}" ] && [ -d "$path/Bahamut/mainnet" ]; then
    rm -rf $path/Bahamut/sahara
    mv -f $path/Bahamut/mainnet $path/Bahamut/sahara
fi

if [ "mainnet" == "$network" ]; then
    network="sahara"
fi
##############################################


function read_confirmation()
{
    OIFS=$IFS
    IFS='/ or'
    while [ true ]; do
        read -p "$1 [$2] " -r
        v=$(echo "$REPLY" | tr '[:upper:]' '[:lower:]')
        for x in $2; do
            c=$(echo "$x" | tr '[:upper:]' '[:lower:]')
            if [ "$c" == "$v" ]; then
                IFS=$OIFS
                echo $x
                return
            fi
        done

        if [ "$v" == "yes" ] || [ "$v" == "y" ]; then
            IFS=$OIFS
            echo "Y"
            return
        elif [ "$v" == "no" ]; then
            IFS=$OIFS
            echo "No"
            return
        fi
    done
}

function check_install_dependency
{
    if ! which wget > /dev/null 2>&1; then
        error "The wget could not be found. You need to install wget to run the script."
        exit 1
    fi
    if ! which tr > /dev/null 2>&1; then
        error "The tr could not be found. You need to install tr to run the script."
        exit 1
    fi
    if ! which curl > /dev/null 2>&1; then
        error "The curl could not be found. You need to install curl to run the script."
        exit 1
    fi
}

function check_start_dependency
{
    for i in $projects; do
        if [ ! -f "$path/Bahamut/${i}" ]; then
            error "The ${i} file not found. Please do the following first ./bahamut install"
            exit 1
        fi
        if [ ! -x "$path/Bahamut/${i}" ]; then
            error "The ${i} is not executable. Please do the following first ./bahamut install"
            exit 1
        fi
    done
}

function check_stop_dependency_and_init
{
    if [ -z "$network" ]; then
        local c=0
        local n=""
        local p=$(pidof $projects)
        if [ ! -z "$p" ]; then
            for i in $network_name; do
                local o=$(ps -fp $p)
                if echo "$o" | grep -q $i; then
                    ((c=c+1))
                    n=$i
                fi
            done
        fi
        if [ 0 -eq $c ]; then
            info "There is no running process."
            exit 0
        elif [ $c -eq 1 ]; then
            network=$n
        else
            error "Sahara and Oasis are currently working. To restart, please indicate which network you want to ${action} example (./bahamut ${action} -n=oasis)."
            exit 1
        fi
    fi
}

function check_update_and_reset_dependency
{
    if [ ! -d $path/Bahamut ]; then
        error "Please do the following first ./bahamut install"
        exit 1
    fi
    for i in $network_name; do
        for j in $projects; do
            if [ ! -z "${project_pids["${i}_${j}_pid"]}" ]; then
                error "To ${action}, it is necessary to stop the running processes. ./bahamut stop"
                exit 1
            fi
        done
    done
}

function check_versions_flag
{
    if [ $github_version_count -ge 2 ]; then
        error "The version flag cannot be specified more than once."
        exit 1
    fi
    if ! [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        error "Invalid github version number format. Please use the format (example v1.0.0)."
        exit 1
    else
        local t=$(curl -s "$binaries_tags_url" | grep -oP '"name": "\K[^"]+')
        if ! [[ $t =~ (^|[[:space:]])"$version"($|[[:space:]]) ]]; then
            error "The entered version was not found on github."
            exit 1
        fi
    fi
}

function read_confirmation_and_stop
{
    local c=$(read_confirmation "$(conf "Do you want to ${action} running ${1} ${2} process? Enter:")" "Y/n")
    if [ "Y" == "$c" ]; then
        kill_process $1 $2 $3 "-15"
        `ps -p $3` > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            kill_process $1 $2 $3 "-9"
        fi
    fi
}

function download_binaries_and_extract
{
    if [ "install" == "$action" ] && [ -x "$path/Bahamut/$1" ]; then
        info "The ${1} binary is exist."
    else
        info "Starting the process of downloading ${1} binaries file. Please wait."
        local j=$(curl -s -i -H "Accept: application/vnd.github.v3+json" "$binaries_releases_url")
        local urls=$(grep browser_download_url <<< "$j" | sed 's/.*"browser_download_url": "\(.*\)"/\1/')
        local url=$(echo "$urls" | grep -o "https://[^ ]*${1}[^ ]*")
        wget -P $download_path/ $url -q --show-progress
        if ! [ $? -eq 0 ]; then
            error "Failed to download the binaries."
            exit 1
        fi
        cd $download_path
        for file in $(ls | grep tar.gz); do
            start_spinner "Starting the process of extract ${1} binary file. Please wait.."
            tar -xzf $file > /dev/null 2>&1 && rm $file > /dev/null 2>&1
            if ! [ $? -eq 0 ]; then
                error "Failed to extract or remove ${1} binaries file."
                exit 1
            else
                stop_spinner
            fi
            info "Starting the process of extract ${1} binary file. Please wait. Done."
        done
        cd - > /dev/null
        mv -f $download_path/$1 $path/Bahamut/ > /dev/null 2>&1
        if ! [ $? -eq 0 ]; then
            error "Failed to move ${1} binaries file."
            exit 1
        fi
    fi
}

function download_bahamut_validator_script
{
    echo -ne $(info "Starting the process of downloading ${script_name} script...")
    wget -P $download_path/ $bahamut_validator_script_url > /dev/null 2>&1
    if ! [ $? -eq 0 ]; then
        error "Failed to download the ${script_name} script."
        exit 1
    fi
    chmod +x $download_path/$script_name
    mv -f $download_path/$script_name $path > /dev/null 2>&1
    echo " Done"
}

function get_systemctl_files_path
{
    echo "/etc/systemd/system/bahamut_${1}_${2}.service"
}

function get_systemctl_validator_start
{
    echo "ExecStart=${path}/Bahamut/${2} --${1} --accept-terms-of-use --wallet-dir="${path}/Bahamut/${1}/datadirs/validator/wallet" --wallet-password-file="${path}/Bahamut/${1}/datadirs/validator/wallet_password.txt" --datadir="${path}/Bahamut/${1}/datadirs/validator" --suggested-fee-recipient="${fee_recipient}" --beacon-rpc-provider="127.0.0.1:${ports[${1}.rpc-port]}""
}

function generate_systemctl_files
{
    local u=$(whoami)
    local exec_start=$(get_systemctl_${2}_start ${1} ${2})
    local systemctl_file=$(get_systemctl_files_path ${1} ${2})
    local service_file_content="[Unit]
Description=The ${2} layer node

[Service]
WorkingDirectory=${path}
ExecStartPre=/bin/chmod +x ${path}/Bahamut/${2}
${exec_start}
User=${u}
Group=${u}
Type=simple
KillSignal=SIGINT
TimeoutStopSec=120
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target"
    echo "$service_file_content" | sudo tee "${systemctl_file}" > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Failed to create the file."
    fi
    echo -ne $(info "Starting the generate ${1} ${2} system file...")
    echo " Done"
}

function init_directory
{
    for i in $network_name; do
        for j in $projects; do
            mkdir -p $path/Bahamut/${i}/datadirs/${j}
            mkdir -p $path/Bahamut/${i}/log/${j}
        done
    done
    rm -rf $download_path
    mkdir -p $download_path
}

function init_systemctl
{
    c=$(read_confirmation "$(conf "Would you like to run the script with systemctl? Enter:")" "Y/n")
    if [ "Y" == "$c" ]; then
        info "This script requires root privileges."
		read_fee_recipient
        for i in $projects; do
            for j in $network_name; do
                service_file=${j}_${i}_system_file
                service_file_name="bahamut_${j}_${i}.service"
                if [ ! -f "${!service_file}" ]; then
                    generate_systemctl_files $j $i
                    sudo systemctl enable $service_file_name > /dev/null 2>&1
                else
                    info "The ${service_file_name} file is exist."
                fi
            done
        done
        info "The systemctl files are enabled."
        info "Systemctl commands examples - sudo systemctl start/stop/restart/status bahamut_oasis_execution.service."
    else
        info "Deny operation with systemctl."
    fi
}

function install_function
{
    check_install_dependency
    check_versions_flag
    init_directory
    for i in $projects; do
        download_binaries_and_extract $i
    done
    install_deposit_cli
    install_deposit_input
    rm -rf $download_path
    init_systemctl
}

function install_deposit_cli
{
	download_binaries_and_extract deposit
}

function install_deposit_input
{
       download_binaries_and_extract deposit-input
}

function read_password
{
	unset password
	prompt="Enter wallet password: "
	while IFS= read -p "$prompt" -r -s -n 1 char
	do
	    if [[ $char == $'\0' ]]
	    then
	        break
	    fi
	    prompt='*'
	    password+="$char"
	done
	echo "$password"
	echo "$password" > "${path}/Bahamut/${network}/datadirs/validator/wallet_password.txt"
}

function check_password_file
{
	if ! [ -f "${path}/Bahamut/${network}/datadirs/validator/wallet_password.txt" ]; then
		read_password
	fi
}

function start_validator
{
    echo -ne $(info "Starting the new ${network} ${1} process...")
    local validator_log_file="$path/Bahamut/${network}/log/validator/${1}_`date +\"%Y_%m_%d_%T\"`"
    nohup $path/Bahamut/$1 \
		--${network} \
		--accept-terms-of-use \
		--wallet-dir="${path}/Bahamut/${network}/datadirs/validator/wallet" \
		--wallet-password-file="${path}/Bahamut/${network}/datadirs/validator/wallet_password.txt" \
		--datadir="${path}/Bahamut/${network}/datadirs/validator" \
		--suggested-fee-recipient="${fee_recipient}" \
		--beacon-rpc-provider="127.0.0.1:${ports[${network}.rpc-port]}" > $validator_log_file 2>&1 &
    echo " Done"
}

function start_function
{
    check_network
    check_start_dependency
	read_fee_recipient
	check_fee_recipient
	check_password_file
    for i in $projects; do
        if [ "${project_pids[${network}_${i}_pid]}" ]; then
            error "The process $network ${i} is already started with pid="${project_pids[${network}_${i}_pid]}""
            continue
        else
            start_${i} ${i}
        fi
    done
}

function kill_process
{
    if [ "$3" ]; then
        local count=0
        echo -ne $(info "Stopping the ${1} ${2} process with pid=${3}...")
        kill $4 $3
        while ps -p $3 > /dev/null; do
            sleep 2
            ((count=count + 1))
            if [[ $count -ge $kill_attempt_count ]]; then
                echo -ne $(info "The ${1} ${2} process does not shut down. Please wait...")
                break
            fi
        done
        echo " Done"
    fi
}

function stop_function
{
    check_stop_dependency_and_init
    for i in $projects; do
        if [ "${project_pids[${network}_${i}_pid]}" ]; then
            read_confirmation_and_stop $network $i "${project_pids[${network}_${i}_pid]}"
        else
            info "There is no ${network} ${i} running process."
        fi
    done
}

function restart_function
{
    stop_function
    for key in "${!project_pids[@]}"; do
        unset project_pids["$key"]
    done
    start_function
}

function update_function
{
    check_versions_flag
    check_update_and_reset_dependency
    rm -rf $download_path
    mkdir -p $path/download
    for i in $projects; do
        download_binaries_and_extract $i
    done
    download_bahamut_validator_script
	install_deposit_cli
    rm -rf $download_path
}

function reset_function
{
    local p=""
    check_update_and_reset_dependency
    if [ -z "$network" ]; then
        p="Network not specified. Do you want to drop oasis and sahara entire contents of databases? Enter:"
        network="sahara oasis"
    else
        p="Do you want to drop ${network} entire contents of database? Enter:"
    fi
    c=$(read_confirmation "$(conf "${p}")" "Y/n")
    if [ "Y" == "$c" ]; then
        for i in $network; do
            for j in $projects; do
                if [ -z "$(ls -A $path/Bahamut/${i}/datadirs/${j}/)" ]; then
                    info "The ${i} ${j} databases have been cleared."
                else
                    rm -rf $path/Bahamut/${i}/datadirs/${j}/*
                    if [ $? -eq 0 ]; then
                        info "The ${i} ${j} database cleanup completed successfully."
                    else
                        error "Failed to clear databaes ${i} ${j}."
                        exit 1
                    fi
                fi
            done
        done
    else
        info "Deny action with reset."
        exit 0
    fi
}

function check_validator_keys_dir
{
	if [ -z $validator_keys_dir ]; then
        error "Validator keys dir is mandatory option during import. Type --help or -h to see the correct options."
        exit 1
	fi
	if ! [ -d $validator_keys_dir ]; then
        error "Validator keys dir must be valid directory. Type --help or -h to see the correct options."
        exit 1
	fi
}

function check_public_keys
{
	if [ -z $public_keys ]; then
        error "Public keys is mandatory option during this operation. Type --help or -h to see the correct options."
        exit 1
	fi
}

function import_function
{
	check_validator_keys_dir
	check_network
	$path/Bahamut/validator accounts import \
		--${network} \
		--accept-terms-of-use \
		--wallet-dir="$path/Bahamut/${network}/datadirs/validator/wallet" \
		--keys-dir="${validator_keys_dir}"
}

function list_function
{
	check_network
	$path/Bahamut/validator accounts list \
		--${network} \
		--accept-terms-of-use \
		--wallet-dir="$path/Bahamut/${network}/datadirs/validator/wallet"
}

function exit_function
{
	check_network
	check_public_keys	
	local o = ""
	if [[ "all" = ${public_keys} ]]; then
		o="--exit-all"
	else
		o="--public-keys ${public_keys}"
	fi
	$path/Bahamut/validator accounts voluntary-exit $o \
		--${network} \
		--accept-terms-of-use \
		--wallet-dir="$path/Bahamut/${network}/datadirs/validator/wallet"
}

function remove_function
{
	check_network
	check_public_keys	
	$path/Bahamut/validator accounts delete $o \
		--${network} \
		--delete-public-keys="${public_keys}" \
		--accept-terms-of-use \
		--wallet-dir="$path/Bahamut/${network}/datadirs/validator/wallet"
}

${action}_function
